### ISSUE TITLE
Getting Error after executing obfuscated python payload

### ISSUE THREAD

**Issue by ZwNagi** [1captainnemo1/Fernet_Obfuscator#1] opened 2020-07-19 17:44 UTC
root@kali:# python obfuscated.py
Traceback (most recent call last):
  File "FinalPayload1199014096.py", line 8, in <module>
    exec(f_obj.decrypt(enc_pay))
  File "<string>", line 1, in <module>
  File "<string>", line 13, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)>

**Comment by ZwNagi** [comment] 2020-07-19 17:58
> root@kali:# python obfuscated.py
> Traceback (most recent call last):
> File "FinalPayload1199014096.py", line 8, in
> exec(f_obj.decrypt(enc_pay))
> File "", line 1, in
> File "", line 13, in
> File "/usr/lib/python2.7/urllib2.py", line 429, in open
> response = self._open(req, data)
> File "/usr/lib/python2.7/urllib2.py", line 447, in _open
> '_open', req)
> File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
> result = func(*args)
> File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
> context=self._context)
> File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
> raise URLError(err)
> urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)>

its solved now its my mistake.

**Comment by 1captainnemo1** [comment] 2020-07-21 01:53
You had a syntactical error .....
Glad to know the issue is resolved now ..
I will be closing this issuw with that knowledge 

Feel free to reach out if you face any further issues 

#Captain_Nemo

**Closed as completed by 1captainnemo1** 2020-07-21 01:53 UTC
